configuration fix

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -700,7 +700,6 @@ ARCHIVE_CPPFLAGS
 ARCHIVE_LIBS
 ARCHIVE_PLTARGETS
 ARCHIVE_TARGETS
-CLIB_FLAGS_LIBUUID
 CLIB_LIBUUID
 CLIB_CRYPTOBJ
 CLIB_CRYPTLIBS
@@ -11802,7 +11801,6 @@ fi
 
 
 
-
 CLIB_TARGETS="socket.$SO cgi.$SO memfile.$SO files.$SO mime.$SO crypt.$SO time.$SO"
 
 case "$PLARCH" in
@@ -11982,69 +11980,7 @@ fi
 fi
 
 
-dl to be installed in various places.
 
-# brew in OSX
-if test -d /usr/local/opt/ossp-uuid; then
-  CPPFLAGS="$CPPFLAGS -I /usr/local/opt/ossp-uuid/include"
-  UUID_LIB_PATH="-L /usr/local/opt/ossp-uuid/lib"
-fi
-
-# /opt
-if test -d /opt/include/ossp; then
-  CPPFLAGS="$CPPFLAGS -I /opt/include"
-  UUID_LIB_PATH="-L /opt/lib"
-fi
-
-# /usr/local
-if test -d /opt/include/ossp; then
-  CPPFLAGS="$CPPFLAGS -I /opt/include"
-  UUID_LIB_PATH="-L /opt/lib"
-fi
-
-if test x"$UUID_H" = "x"; then
-  ac_fn_c_check_header_compile "$LINENO" "ossp/uuid.h" "ac_cv_header_ossp_uuid_h" "/*first*/
-"
-if test "x$ac_cv_header_ossp_uuid_h" = xyes; then :
-   UUID_H=ossp/uuid.h
-		    has_uuid=true
-fi
-
-
-fi
-if test x"$UUID_H" = "x" -a ! -d /usr/include/uuid; then
-  ac_fn_c_check_header_compile "$LINENO" "uuid/uuid.h" "ac_cv_header_uuid_uuid_h" "/*first*/
-"
-if test "x$ac_cv_header_uuid_uuid_h" = xyes; then :
-   UUID_H=uuid/uuid.h
-		    has_uuid=true
-fi
-
-
-fi
-if test x"$UUID_H" = "x"; then
-  ac_fn_c_check_header_compile "$LINENO" "uuid.h" "ac_cv_header_uuid_h" "/*first*/
-"
-if test "x$ac_cv_header_uuid_h" = xyes; then :
-   UUID_H=uuid.h
-		    has_uuid=true
-fi
-
-
-fi
-if test x"$UUID_H" = "x"; then
-    { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING:  Cannot find uuid.h -- dropping uuid.pl" >&5
-$as_echo "$as_me: WARNING:  Cannot find uuid.h -- dropping uuid.pl" >&2;}
-else
-
-cat >>confdefs.h <<_ACEOF
-#define UUID_H <$UUID_H>
-_ACEOF
-
-    has_uuid=true
-fi
-
-if test x"$has_uuid" != "x"; then
 ac_fn_c_check_func "$LINENO" "uuid_create" "ac_cv_func_uuid_create"
 if test "x$ac_cv_func_uuid_create" = xyes; then :
   has_uuid=true
@@ -12088,7 +12024,7 @@ fi
 { $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_uuid_uuid_create" >&5
 $as_echo "$ac_cv_lib_uuid_uuid_create" >&6; }
 if test "x$ac_cv_lib_uuid_uuid_create" = xyes; then :
-   CLIB_LIBUUID="$UUID_LIB_PATH -luuid"
+   CLIB_LIBUUID=-luuid
 	        has_uuid=true
 
 fi
@@ -12102,6 +12038,45 @@ $as_echo "$as_me: WARNING:  Cannot find libossp-uuid or libuuid -- dropping uuid
 
 fi
 
+if test x"$has_uuid" != "x"; then
+  if test x"$UUID_H" = "x"; then
+  ac_fn_c_check_header_compile "$LINENO" "ossp/uuid.h" "ac_cv_header_ossp_uuid_h" "/*first*/
+"
+if test "x$ac_cv_header_ossp_uuid_h" = xyes; then :
+   UUID_H=ossp/uuid.h
+fi
+
+
+  fi
+  if test x"$UUID_H" = "x" -a ! -d /usr/include/uuid; then
+  ac_fn_c_check_header_compile "$LINENO" "uuid/uuid.h" "ac_cv_header_uuid_uuid_h" "/*first*/
+"
+if test "x$ac_cv_header_uuid_uuid_h" = xyes; then :
+   UUID_H=uuid/uuid.h
+fi
+
+
+  fi
+  if test x"$UUID_H" = "x"; then
+  ac_fn_c_check_header_compile "$LINENO" "uuid.h" "ac_cv_header_uuid_h" "/*first*/
+"
+if test "x$ac_cv_header_uuid_h" = xyes; then :
+   UUID_H=uuid.h
+fi
+
+
+  fi
+  if test x"$UUID_H" = "x"; then
+    { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING:  Cannot find uuid.h -- dropping uuid.pl" >&5
+$as_echo "$as_me: WARNING:  Cannot find uuid.h -- dropping uuid.pl" >&2;}
+  else
+
+cat >>confdefs.h <<_ACEOF
+#define UUID_H <$UUID_H>
+_ACEOF
+
+    CLIB_TARGETS="$CLIB_TARGETS uuid.$SO"
+  fi
 fi
 
 
@@ -14342,7 +14317,7 @@ else
 JAVA_TEST=Test.java
 CLASS_TEST=Test.class
 cat << \EOF > $JAVA_TEST
-/* #line 14345 "configure" */
+/* #line 14320 "configure" */
 public class Test {
 }
 EOF
@@ -14518,7 +14493,7 @@ EOF
 if uudecode$EXEEXT Test.uue; then
         ac_cv_prog_uudecode_base64=yes
 else
-        echo "configure: 14521: uudecode had trouble decoding base 64 file 'Test.uue'" >&5
+        echo "configure: 14496: uudecode had trouble decoding base 64 file 'Test.uue'" >&5
         echo "configure: failed file was:" >&5
         cat Test.uue >&5
         ac_cv_prog_uudecode_base64=no
@@ -14649,7 +14624,7 @@ else
 JAVA_TEST=Test.java
 CLASS_TEST=Test.class
 cat << \EOF > $JAVA_TEST
-/* #line 14652 "configure" */
+/* #line 14627 "configure" */
 public class Test {
 }
 EOF
@@ -14684,7 +14659,7 @@ JAVA_TEST=Test.java
 CLASS_TEST=Test.class
 TEST=Test
 cat << \EOF > $JAVA_TEST
-/* [#]line 14687 "configure" */
+/* [#]line 14662 "configure" */
 public class Test {
 public static void main (String args[]) {
         System.exit (0);
@@ -17702,7 +17677,6 @@ PKG_PROSQLITE="packages/prosqlite"
 
 yap_cv_prosqlite=yes
 
-yap_cv_prosqlite=yes
 
 # Check whether --with-prosqlite was given.
 if test "${with_prosqlite+set}" = set; then :
@@ -17710,9 +17684,8 @@ if test "${with_prosqlite+set}" = set; then :
 	    PROSQLITE_DIR=/usr
 	elif test "$withval" = no; then
 	    yap_cv_prosqlite=no
-
-else
-	    PROSQLITE_DIR=$withval
+	else
+	    PROSQLITE_DIR="$withval"
 	fi
 else
   PROSQLITE_DIR=/usr
@@ -17730,7 +17703,6 @@ if test $yap_cv_prosqlite = yes; then
   if test ! -z "$PROSQLITE_DIR"; then
     PROSQLITE_CPPFLAGS="-I${PROSQLITE_DIR}/include"
     PROSQLITE_LDFLAGS="-L${PROSQLITE_DIR}/lib"
-    CPPFLAGS="-I${PROSQLITE_DIR}/include ${CPPFLAGS}"
     CPPFLAGS="-I${PROSQLITE_DIR}/include ${CPPFLAGS}"
     CIFLAGS="-I${PROSQLITE_DIR}/include ${CIFLAGS}"
     LDFLAGS="-L${PROSQLITE_DIR}/lib ${LDFLAGS}"
@@ -17798,13 +17770,13 @@ done
 
 fi
 
-
-if test "$havelib" = yes &&
-    test "$ac_cv_header_sqlite3_h" = yes; then
+if test "$yap_cv_prosqlite" != no &&
+   test	"$havelib" = yes &&
+   test	"$ac_cv_header_sqlite3_h" = yes; then
   PROSQLITE_TARGETS="prosqlite.$SO"
   PROSQLITE_PLTARGETS="prolog/prosqlite.pl"
 else
-  echo "ERROR:   Cannot find odbc library or the header sql.h"
+  echo "ERROR:   Cannot find sqlite3 library and/or the header sqlite3.h"
   echo "WARNING: PROSQLITE interface will not be built"
   PROSQLITE_TARGETS=""
 fi
@@ -17818,16 +17790,14 @@ fi
 
 
 
+yap_timestamp=`date`
+yap_nversion=`expr $YAP_MAJOR_VERSION \* 10000 + $YAP_MINOR_VERSION \* 100 + $YAP_POINT_VERSION`
+yap_startup=startup.yss
 
 
 cat >>confdefs.h <<_ACEOF
 #define YAP_STARTUP  "$yap_startup"
 _ACEOF
-
-
-yap_timestamp=`date`
-yap_nversion=`expr $YAP_MAJOR_VERSION \* 10000 + $YAP_MINOR_VERSION \* 100 + $YAP_POINT_VERSION`
-yap_startup=startup.yss
 
 
 cat >>confdefs.h <<_ACEOF
