update configuration script to avoid incompatible options`
git-svn-id: https://yap.svn.sf.net/svnroot/yap/trunk@1330 b08c6af1-5177-4d33-ba66-4b1c6b8b522a

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -15,27 +15,40 @@ AC_SUBST(GCC)
 AC_SUBST(C_INTERF_FLAGS)
 AC_SUBST(C_PARSER_FLAGS)
 
+AC_ARG_ENABLE(tabling,
+	[ --enable-tabling           support tabling ],
+	tabling="$enableval", tabling=no)
+AC_ARG_ENABLE(or-parallelism,
+	[ --enable-or-parallelism    support or-parallelism as: env-copy,sba,a-cow ],
+	orparallelism="$enableval", orparallelism=no)
+if test "$tabling" = yes -o "$orparallelism" = yes -o "$threads" = yes
+then
+AC_ARG_ENABLE(rational-trees,
+	[ --enable-rational-trees    support infinite rational trees ],
+	rationaltrees="$enableval" ; rationaltrees=yes)
+AC_ARG_ENABLE(coroutining,
+	[ --enable-coroutining       support co-routining, attributed variables and constraints],
+	rationaltrees="$enableval";coroutining="$enableval", coroutining=no)
+AC_ARG_ENABLE(depth-limit,
+	[ --enable-depth-limit       support depth-bound computation ],
+	depthlimit="$enableval", depthlimit=no)
+else
 AC_ARG_ENABLE(rational-trees,
 	[ --enable-rational-trees    support infinite rational trees ],
 	rationaltrees="$enableval" ; rationaltrees=no)
 AC_ARG_ENABLE(coroutining,
 	[ --enable-coroutining       support co-routining, attributed variables and constraints],
 	rationaltrees="$enableval";coroutining="$enableval", coroutining=yes)
-AC_ARG_ENABLE(wam-profile,
-	[ --enable-wam-profile       support low level profiling of abstract machine ],
-	wamprofile="$enableval", wamprofile=no)
 AC_ARG_ENABLE(depth-limit,
 	[ --enable-depth-limit       support depth-bound computation ],
 	depthlimit="$enableval", depthlimit=yes)
-AC_ARG_ENABLE(or-parallelism,
-	[ --enable-or-parallelism    support or-parallelism as: env-copy,sba,a-cow ],
-	orparallelism="$enableval", orparallelism=no)
+fi
+AC_ARG_ENABLE(wam-profile,
+	[ --enable-wam-profile       support low level profiling of abstract machine ],
+	wamprofile="$enableval", wamprofile=no)
 AC_ARG_ENABLE(low-level-tracer,
 	[ --enable-low-level-tracer  support support for procedure-call tracing ],
 	lowleveltracer="$enableval", lowleveltracer=no)
-AC_ARG_ENABLE(tabling,
-	[ --enable-tabling           support tabling ],
-	tabling="$enableval", tabling=no)
 AC_ARG_ENABLE(threads,
 	[ --enable-threads           support system threads ],
 	threads="$enableval", threads=no)
@@ -176,9 +189,42 @@ AC_ARG_WITH(trail-space,
 
 if test "$tabling" = yes -o "$orparallelism" = yes -o "$threads" = yes
 then
-	AC_DEFINE(MinHeapSpace, (400*SIZEOF_INT_P))
-	AC_DEFINE(MinStackSpace,(300*SIZEOF_INT_P))
-	AC_DEFINE(MinTrailSpace,( 48*SIZEOF_INT_P))
+  AC_DEFINE(MinHeapSpace, (400*SIZEOF_INT_P))
+  AC_DEFINE(MinStackSpace,(300*SIZEOF_INT_P))
+  AC_DEFINE(MinTrailSpace,( 48*SIZEOF_INT_P))
+  if test "$coroutining" = yes 
+  then
+   echo
+   echo
+   echo "********************************************************"
+   echo
+   echo
+   echo "!!!!!! ERROR !!!!!"
+   echo "Coroutining is currently incompatible with Tabling/Parallelism/Threads"
+   echo "Please contact ricroc@ncc.up.pt for help" 
+   echo
+   echo
+   echo "********************************************************"
+   echo
+   echo
+   exit 1
+  fi
+  if test "$depthlimit" = yes -a "$tabling" = yes
+  then
+   echo
+   echo
+   echo "********************************************************"
+   echo
+   echo
+   echo "!!!!!! WARNING !!!!!!"
+   echo "Depth Limit makes no sense with Tabling"
+   echo "Please contact ricroc@ncc.up.pt for help" 
+   echo
+   echo
+   echo "********************************************************"
+   echo
+   echo
+  fi
 else
 	AC_DEFINE(MinHeapSpace, (200*SIZEOF_INT_P))
 	AC_DEFINE(MinStackSpace,(200*SIZEOF_INT_P))
